apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders-service
  namespace: orders-prod
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-service
